[workspace]
members = [
    "examples/example-runner-cpu",
    "examples/example-runner",
    "examples/example-shader",
    "rustc_codegen_spirv",
    "spirv-builder",
    "spirv-std",
]

[patch.crates-io]
rspirv = { git = "https://github.com/gfx-rs/rspirv.git", rev = "f11f8797bd4df2d1d22cf10767b39a5119c57551" }

# https://github.com/bitshifter/glam-rs/pull/85
glam = { git = "https://github.com/EmbarkStudios/glam-rs", rev = "0c13d3a" }
